using Foodiya.Application.Interfaces.Auth;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Infrastructure.Data;
using Foodiya.Infrastructure.Data.Repositories;
using Foodiya.Infrastructure.Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Foodiya.Infrastructure.Extensions.Data
{
    public static partial class ServiceCollectionExtensions
    {
        public static void AddRepositories(this IServiceCollection services, IConfiguration configuration, bool isDevelopment = false)
        {
            services.AddDbContext<AutoGeneratedDbContext>(options =>
            {
                options.UseSqlServer(configuration.GetConnectionString("DefaultConnection"));

                if (isDevelopment)
                {
                    options.EnableDetailedErrors();
                    options.EnableSensitiveDataLogging();
                }
            });

            // Generic Repository — one open-generic registration covers every entity type
            services.AddScoped(typeof(IGenericRepository<>), typeof(GenericRepository<>));

            // Specialized repositories
            services.AddScoped<IAppUserExternalLoginRepository, AppUserExternalLoginRepository>();
            services.AddScoped<IRecipeRepository, RecipeRepository>();
            services.AddScoped<IFoodCategoryRepository, FoodCategoryRepository>();
            services.AddScoped<ICuisineRepository, CuisineRepository>();
            services.AddScoped<IDifficultyRepository, DifficultyRepository>();
            services.AddScoped<IIngredientRepository, IngredientRepository>();
            services.AddScoped<IIngredientImageRepository, IngredientImageRepository>();
            services.AddScoped<IIngredientTypeRepository, IngredientTypeRepository>();
            services.AddScoped<IMoroccanCityRepository, MoroccanCityRepository>();
            services.AddScoped<IMoroccanRegionRepository, MoroccanRegionRepository>();
            services.AddScoped<IPresetAvatarImageRepository, PresetAvatarImageRepository>();
            services.AddScoped<IRecipeImageRepository, RecipeImageRepository>();
            services.AddScoped<IRecipeIngredientRepository, RecipeIngredientRepository>();
            services.AddScoped<IRecipeLikeRepository, RecipeLikeRepository>();
            services.AddScoped<IRecipeNutritionRepository, RecipeNutritionRepository>();
            services.AddScoped<IRecipeShareRepository, RecipeShareRepository>();
            services.AddScoped<IRecipeStepRepository, RecipeStepRepository>();
            services.AddScoped<IUnitRepository, UnitRepository>();
            services.AddScoped<IReferenceDataRepository, ReferenceDataRepository>();
            services.AddScoped<IGoogleIdTokenValidator, GoogleIdTokenValidator>();
            services.AddScoped<IAccessTokenService, JwtAccessTokenService>();
            services.AddScoped<IRefreshTokenService, RefreshTokenService>();
            services.AddScoped<IPasswordHasherService, PasswordHasherService>();
        }
    }
}
