using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class AppUserExternalLoginRepository : GenericRepository<AppUserExternalLogin>, IAppUserExternalLoginRepository
{
    public AppUserExternalLoginRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
