using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public class CuisineRepository : GenericRepository<Cuisine>, ICuisineRepository
{
    public CuisineRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
