using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public class DifficultyRepository : GenericRepository<Difficulty>, IDifficultyRepository
{
    public DifficultyRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
