using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public class FoodCategoryRepository : GenericRepository<FoodCategory>, IFoodCategoryRepository
{
    public FoodCategoryRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
