using AutoMapper;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Foodiya.Domain.Exceptions;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Interfaces.Specifications;

namespace Foodiya.Infrastructure.Data.Repositories;

/// <summary>
/// Generic EF Core repository.
/// Provides sync/async CRUD, specification-based querying, projected mapping,
/// paginated results, SQL duplicate-key handling, and transaction support.
/// </summary>
public class GenericRepository<T> : IGenericRepository<T> where T : class
{
    #region "Attributes"
    protected readonly AutoGeneratedDbContext context;
    protected readonly IMapper mapper;
    protected DbSet<T> entities;
    #endregion

    #region "Constructors"
    public GenericRepository(AutoGeneratedDbContext context, IMapper mapper)
    {
        this.context = context;
        this.mapper = mapper;
        entities = context.Set<T>();
    }
    #endregion

    #region "Sync Methods"

    public T? GetById(int id, ISpecification<T>? specification = null)
    {
        if (specification == null)
            return entities.Find(id);

        return SpecificationEvaluator<T>.GetQuery(entities, specification).FirstOrDefault();
    }

    public T? GetSingle(ISpecification<T> specification)
    {
        return SpecificationEvaluator<T>.GetQuery(entities, specification).FirstOrDefault();
    }

    /// <summary>
    /// Returns an IQueryable that can be further composed. If a specification is provided,
    /// criteria, includes, and ordering are applied.
    /// </summary>
    public IQueryable<T> GetAll(ISpecification<T>? specification = null)
    {
        if (specification == null)
            return entities;

        return SpecificationEvaluator<T>.GetQuery(entities, specification);
    }

    /// <summary>
    /// Executes the query and projects (maps) the result to the requested DTO type.
    /// </summary>
    public IEnumerable<TProjectTo> GetAll<TProjectTo>(ISpecification<T>? specification = null)
    {
        IQueryable<T> query = specification == null
            ? entities
            : SpecificationEvaluator<T>.GetQuery(entities, specification);

        return mapper.Map<IEnumerable<TProjectTo>>(query).AsEnumerable();
    }

    #endregion

    #region "Async Methods"

    public async Task<T?> GetByIdAsync(int id, ISpecification<T>? specification = null, CancellationToken ct = default)
    {
        if (specification == null)
            return await entities.FindAsync([id], ct);

        return await SpecificationEvaluator<T>.GetQuery(entities, specification).FirstOrDefaultAsync(ct);
    }

    public async Task<T?> GetSingleAsync(ISpecification<T> specification, CancellationToken ct = default)
    {
        return await SpecificationEvaluator<T>.GetQuery(entities, specification).FirstOrDefaultAsync(ct);
    }

    public async Task<int> CountAsync(ISpecification<T> specification, CancellationToken ct = default)
    {
        if (specification == null) throw new FoodiyaBadRequestException("Specification cannot be null for count.");
        var query = SpecificationEvaluator<T>.GetQuery(entities, specification);
        return await query.CountAsync(ct);
    }

    public async Task<IReadOnlyList<T>> ListAsync(ISpecification<T> specification, CancellationToken ct = default)
    {
        var query = SpecificationEvaluator<T>.GetQuery(entities, specification);
        query = SpecificationEvaluator<T>.AddPagination(query, specification);
        return await query.ToListAsync(ct);
    }

    /// <summary>
    /// Returns paginated results projected to TProjectTo along with the total count (before pagination).
    /// </summary>
    public async Task<(IEnumerable<TProjectTo> results, int itemsCount)> GetAllPaginated<TProjectTo>(
        ISpecification<T> specification, CancellationToken ct = default)
    {
        var query = SpecificationEvaluator<T>.GetQuery(entities, specification);

        var itemsCount = await query.CountAsync(ct);

        query = SpecificationEvaluator<T>.AddPagination(query, specification);
        var results = mapper.Map<IEnumerable<TProjectTo>>(query);

        return (results.AsEnumerable(), itemsCount);
    }

    #endregion

    #region "Command Methods"

    public async Task<T> InsertAsync(T entity, CancellationToken ct = default)
    {
        if (entity == null)
            throw new FoodiyaNullArgumentException(nameof(entity));

        var result = await entities.AddAsync(entity, ct);
        return result.Entity;
    }

    public T Update(T entity)
    {
        entities.Attach(entity);
        context.Entry(entity).State = EntityState.Modified;
        return entity;
    }

    public void Delete(T entity)
    {
        if (entity == null)
            throw new FoodiyaNullArgumentException(nameof(entity));

        entities.Remove(entity);
    }

    /// <summary>
    /// Saves all pending changes. Catches SQL unique constraint/index violations
    /// (error codes 2627 / 2601) and wraps them in <see cref="FoodiyaValueAlreadyExistsException"/>.
    /// </summary>
    public async Task<int> SaveAsync(CancellationToken ct = default)
    {
        try
        {
            return await context.SaveChangesAsync(ct);
        }
        catch (DbUpdateException ex) when (
            ex.InnerException is SqlException sqlEx &&
            (sqlEx.Number == SqlErrorNumbers.UniqueConstraintViolation
             || sqlEx.Number == SqlErrorNumbers.UniqueIndexViolation))
        {
            throw new FoodiyaValueAlreadyExistsException($"This {typeof(T).Name} already exists", ex);
        }
    }

    public async Task<ITransaction> BeginTransactionAsync(CancellationToken ct = default)
    {
        var efTransaction = await context.Database.BeginTransactionAsync(ct);
        return new EfTransaction(efTransaction);
    }

    #endregion
}
