using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class IngredientImageRepository : GenericRepository<IngredientImage>, IIngredientImageRepository
{
    public IngredientImageRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
