using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class IngredientTypeRepository : GenericRepository<IngredientType>, IIngredientTypeRepository
{
    public IngredientTypeRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
