using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class MoroccanCityRepository : GenericRepository<MoroccanCity>, IMoroccanCityRepository
{
    public MoroccanCityRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
