using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class MoroccanRegionRepository : GenericRepository<MoroccanRegion>, IMoroccanRegionRepository
{
    public MoroccanRegionRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
