using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class PresetAvatarImageRepository : GenericRepository<PresetAvatarImage>, IPresetAvatarImageRepository
{
    public PresetAvatarImageRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
