using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class RecipeImageRepository : GenericRepository<RecipeImage>, IRecipeImageRepository
{
    public RecipeImageRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
