using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class RecipeShareRepository : GenericRepository<RecipeShare>, IRecipeShareRepository
{
    public RecipeShareRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
