using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class RecipeLikeRepository : GenericRepository<RecipeLike>, IRecipeLikeRepository
{
    public RecipeLikeRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
