using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class RecipeNutritionRepository : GenericRepository<RecipeNutrition>, IRecipeNutritionRepository
{
    public RecipeNutritionRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
