using AutoMapper;
using Foodiya.Domain.Constants;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace Foodiya.Infrastructure.Data.Repositories;

/// <summary>
/// Specialized EF Core repository for Recipe entities.
/// Inherits from <see cref="GenericRepository{Recipe}"/> and adds domain-specific query methods.
/// </summary>
public class RecipeRepository : GenericRepository<Recipe>, IRecipeRepository
{
    public RecipeRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }

    public async Task<Recipe?> GetRecipeWithRelationsAsync(int id, CancellationToken ct = default)
    {
        return await context.Recipes
            .AsNoTracking()
            .Include(r => r.Difficulty)
            .Include(r => r.Cuisine)
            .Include(r => r.City)
            .Include(r => r.Chef)
            .Include(r => r.RecipeNutrition)
            .Include(r => r.FoodCategories)
            .Include(r => r.RecipeSteps.OrderBy(s => s.StepNumber))
            .Include(r => r.RecipeImages.OrderBy(i => i.SortOrder))
            .Include(r => r.RecipeIngredients.OrderBy(ri => ri.SortOrder))
                .ThenInclude(ri => ri.Ingredient)
            .Include(r => r.RecipeIngredients)
                .ThenInclude(ri => ri.Unit)
            .Include(r => r.RecipeLikes)
            .Where(r => r.Id == id && r.IsActive && r.DeletedAt == null)
            .FirstOrDefaultAsync(ct);
    }

    public async Task<Recipe?> GetRecipeForUpdateAsync(int id, CancellationToken ct = default)
    {
        return await context.Recipes
            .Include(r => r.FoodCategories)
            .Include(r => r.RecipeSteps)
            .Include(r => r.RecipeIngredients)
            .Where(r => r.Id == id && r.DeletedAt == null)
            .FirstOrDefaultAsync(ct);
    }

    public async Task<IReadOnlyList<Recipe>> SearchRecipesAsync(string searchTerm, CancellationToken ct = default)
    {
        var term = searchTerm.Trim().ToLower();
        return await context.Recipes
            .AsNoTracking()
            .Include(r => r.Difficulty)
            .Include(r => r.Cuisine)
            .Include(r => r.Chef)
            .Include(r => r.FoodCategories)
            .Include(r => r.RecipeLikes)
            .Where(r => r.DeletedAt == null
                        && r.Status == RecipeStatusConstants.Published
                        && r.IsActive
                        && (r.Title.ToLower().Contains(term)
                            || (r.Summary != null && r.Summary.ToLower().Contains(term))))
            .OrderByDescending(r => r.PublishedAt)
            .ToListAsync(ct);
    }

    public async Task<IReadOnlyList<Recipe>> GetRecipesByChefAsync(int chefId, CancellationToken ct = default)
    {
        return await context.Recipes
            .AsNoTracking()
            .Include(r => r.Difficulty)
            .Include(r => r.Cuisine)
            .Include(r => r.FoodCategories)
            .Include(r => r.RecipeLikes)
            .Where(r => r.ChefId == chefId && r.DeletedAt == null)
            .OrderByDescending(r => r.DateInsert)
            .ToListAsync(ct);
    }

    public async Task<IReadOnlyList<Recipe>> GetRecipesByCuisineAsync(int cuisineId, CancellationToken ct = default)
    {
        return await context.Recipes
            .AsNoTracking()
            .Include(r => r.Difficulty)
            .Include(r => r.Cuisine)
            .Include(r => r.Chef)
            .Include(r => r.FoodCategories)
            .Include(r => r.RecipeLikes)
            .Where(r => r.DeletedAt == null
                        && r.CuisineId == cuisineId
                        && r.Status == RecipeStatusConstants.Published
                        && r.IsActive)
            .OrderByDescending(r => r.PublishedAt)
            .ToListAsync(ct);
    }

    public async Task<IReadOnlyList<Recipe>> GetRecipesByDifficultyAsync(int difficultyId, CancellationToken ct = default)
    {
        return await context.Recipes
            .AsNoTracking()
            .Include(r => r.Difficulty)
            .Include(r => r.Cuisine)
            .Include(r => r.Chef)
            .Include(r => r.FoodCategories)
            .Include(r => r.RecipeLikes)
            .Where(r => r.DeletedAt == null
                        && r.DifficultyId == difficultyId
                        && r.Status == RecipeStatusConstants.Published
                        && r.IsActive)
            .OrderByDescending(r => r.PublishedAt)
            .ToListAsync(ct);
    }

    public async Task<IReadOnlyList<Recipe>> GetRecipesByCategoryAsync(int categoryId, CancellationToken ct = default)
    {
        return await context.Recipes
            .AsNoTracking()
            .Include(r => r.Difficulty)
            .Include(r => r.Cuisine)
            .Include(r => r.Chef)
            .Include(r => r.FoodCategories)
            .Include(r => r.RecipeLikes)
            .Where(r => r.DeletedAt == null
                        && r.FoodCategories.Any(c => c.Id == categoryId)
                        && r.Status == RecipeStatusConstants.Published
                        && r.IsActive)
            .OrderByDescending(r => r.PublishedAt)
            .ToListAsync(ct);
    }
}
