using AutoMapper;
using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;

namespace Foodiya.Infrastructure.Data.Repositories;

public sealed class RecipeIngredientRepository : GenericRepository<RecipeIngredient>, IRecipeIngredientRepository
{
    public RecipeIngredientRepository(AutoGeneratedDbContext context, IMapper mapper) : base(context, mapper)
    {
    }
}
