using Foodiya.Domain.Interfaces.Core;
using Foodiya.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace Foodiya.Infrastructure.Data.Repositories;

/// <summary>
/// EF Core implementation that fetches all reference/lookup data.
/// Keeps DbContext usage strictly in the Infrastructure layer.
/// </summary>
public sealed class ReferenceDataRepository : IReferenceDataRepository
{
    private readonly AutoGeneratedDbContext _context;

    public ReferenceDataRepository(AutoGeneratedDbContext context)
    {
        _context = context;
    }

    public async Task<ReferenceData> GetAllReferenceDataAsync(CancellationToken ct = default)
    {
        return new ReferenceData
        {
            Cuisines = await _context.Cuisines
                .AsNoTracking()
                .OrderBy(item => item.Name)
                .Select(item => new ReferenceDataItem
                {
                    Id = item.Id,
                    Label = item.Name
                })
                .ToListAsync(ct),

            Difficulties = await _context.Difficulties
                .AsNoTracking()
                .OrderBy(item => item.SortOrder)
                .ThenBy(item => item.Name)
                .Select(item => new ReferenceDataItem
                {
                    Id = item.Id,
                    Label = item.Name,
                    SortOrder = item.SortOrder
                })
                .ToListAsync(ct),

            FoodCategories = await _context.FoodCategories
                .AsNoTracking()
                .OrderBy(item => item.Name)
                .Select(item => new ReferenceDataItem
                {
                    Id = item.Id,
                    Label = item.Name,
                    Description = item.Description
                })
                .ToListAsync(ct),

            IngredientTypes = await _context.IngredientTypes
                .AsNoTracking()
                .OrderBy(item => item.Label)
                .Select(item => new ReferenceDataItem
                {
                    Id = item.Id,
                    Code = item.Code,
                    Label = item.Label
                })
                .ToListAsync(ct),

            Units = await _context.Units
                .AsNoTracking()
                .OrderBy(item => item.Label)
                .Select(item => new ReferenceDataItem
                {
                    Id = item.Id,
                    Code = item.Code,
                    Label = item.Label
                })
                .ToListAsync(ct),

            MoroccanRegions = await _context.MoroccanRegions
                .AsNoTracking()
                .OrderBy(item => item.Name)
                .Select(item => new ReferenceDataItem
                {
                    Id = item.Id,
                    Code = item.Code,
                    Label = item.Name
                })
                .ToListAsync(ct),

            MoroccanCities = await _context.MoroccanCities
                .AsNoTracking()
                .OrderBy(item => item.Name)
                .Select(item => new ReferenceDataItem
                {
                    Id = item.Id,
                    Label = item.Name,
                    ParentId = item.RegionId,
                    Slug = item.Slug
                })
                .ToListAsync(ct),

            PresetAvatarImages = await _context.PresetAvatarImages
                .AsNoTracking()
                .OrderBy(item => item.SortOrder)
                .ThenBy(item => item.Label)
                .Select(item => new ReferenceDataItem
                {
                    Id = item.Id,
                    Code = item.Code,
                    Label = item.Label,
                    SortOrder = item.SortOrder,
                    ImageUrl = item.ImageUrl,
                    BackgroundColor = item.BackgroundColor,
                    IsActive = item.IsActive
                })
                .ToListAsync(ct)
        };
    }
}
