using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Foodiya.Domain.Models;

/// <summary>
/// Links an external identity provider (e.g. Google) to an AppUser.
/// EF Core configuration (indexes, unicode, constraints) is in
/// AutoGeneratedDbContext.Auth.cs via Fluent API.
/// </summary>
public sealed class AppUserExternalLogin
{
    [Key]
    public int Id { get; set; }

    public int AppUserId { get; set; }

    [StringLength(50)]
    public string Provider { get; set; } = string.Empty;

    [StringLength(200)]
    public string ProviderSubject { get; set; } = string.Empty;

    [Column(TypeName = "smalldatetime")]
    public DateTime DateInsert { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime LastSignInAt { get; set; }

    [ForeignKey(nameof(AppUserId))]
    public AppUser AppUser { get; set; } = null!;
}
