using System;
using System.Collections.Generic;
using Foodiya.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace Foodiya.Infrastructure.Data;

public partial class AutoGeneratedDbContext : DbContext
{
    public AutoGeneratedDbContext(DbContextOptions<AutoGeneratedDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppUser> AppUsers { get; set; }

    public virtual DbSet<AppUserRefreshToken> AppUserRefreshTokens { get; set; }

    public virtual DbSet<ChefProfile> ChefProfiles { get; set; }

    public virtual DbSet<Cuisine> Cuisines { get; set; }

    public virtual DbSet<DailyRecipeStat> DailyRecipeStats { get; set; }

    public virtual DbSet<Difficulty> Difficulties { get; set; }

    public virtual DbSet<FoodCategory> FoodCategories { get; set; }

    public virtual DbSet<Ingredient> Ingredients { get; set; }

    public virtual DbSet<IngredientImage> IngredientImages { get; set; }

    public virtual DbSet<IngredientType> IngredientTypes { get; set; }

    public virtual DbSet<MoroccanCity> MoroccanCities { get; set; }

    public virtual DbSet<MoroccanRegion> MoroccanRegions { get; set; }

    public virtual DbSet<PresetAvatarImage> PresetAvatarImages { get; set; }

    public virtual DbSet<Recipe> Recipes { get; set; }

    public virtual DbSet<RecipeImage> RecipeImages { get; set; }

    public virtual DbSet<RecipeIngredient> RecipeIngredients { get; set; }

    public virtual DbSet<RecipeLike> RecipeLikes { get; set; }

    public virtual DbSet<RecipeNutrition> RecipeNutritions { get; set; }

    public virtual DbSet<RecipeShare> RecipeShares { get; set; }

    public virtual DbSet<RecipeStep> RecipeSteps { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.ToTable("AppUser", tb => tb.HasTrigger("TR_AppUser_GenerateCode"));

            entity.HasIndex(e => e.DeletedAt, "IX_AppUser_DeletedAt");

            entity.HasIndex(e => e.PresetAvatarImageId, "IX_AppUser_PresetAvatarImageId");

            entity.HasIndex(e => e.Role, "IX_AppUser_Role");

            entity.HasIndex(e => e.Code, "UQ_AppUser_Code").IsUnique();

            entity.HasIndex(e => e.Email, "UQ_AppUser_Email").IsUnique();

            entity.HasIndex(e => e.UserName, "UQ_AppUser_UserName").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_AppUser_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_AppUser_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.DeleteReason)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasDefaultValue("", "DF_AppUser_DeleteReason");
            entity.Property(e => e.DeletedAt).HasColumnType("smalldatetime");
            entity.Property(e => e.Email)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_AppUser_IsActive");
            entity.Property(e => e.LastName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PasswordHash).HasMaxLength(1024);
            entity.Property(e => e.PasswordSalt).HasMaxLength(1024);
            entity.Property(e => e.ProfileImageUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Role)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("USER", "DF_AppUser_Role");
            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_AppUser_Uuid");

            entity.HasOne(d => d.DeletedByUser).WithMany(p => p.InverseDeletedByUser)
                .HasForeignKey(d => d.DeletedByUserId)
                .HasConstraintName("FK_AppUser_DeletedByUser");

            entity.HasOne(d => d.PresetAvatarImage).WithMany(p => p.AppUsers)
                .HasForeignKey(d => d.PresetAvatarImageId)
                .HasConstraintName("FK_AppUser_PresetAvatarImage");
        });

        modelBuilder.Entity<AppUserRefreshToken>(entity =>
        {
            entity.ToTable("AppUserRefreshToken", tb => tb.HasTrigger("TR_AppUserRefreshToken_GenerateCode"));

            entity.HasIndex(e => e.AppUserId, "IX_AppUserRefreshToken_AppUserId");

            entity.HasIndex(e => e.TokenHash, "IX_AppUserRefreshToken_TokenHash");

            entity.HasIndex(e => e.Code, "UQ_AppUserRefreshToken_Code").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_AppUserRefreshToken_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ReplacedByTokenHash)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.TokenHash)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_AppUserRefreshToken_Uuid");

            entity.HasOne(d => d.AppUser).WithMany(p => p.AppUserRefreshTokens)
                .HasForeignKey(d => d.AppUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AppUserRefreshToken_AppUser");
        });

        modelBuilder.Entity<ChefProfile>(entity =>
        {
            entity.ToTable("ChefProfile", tb => tb.HasTrigger("TR_ChefProfile_GenerateCode"));

            entity.HasIndex(e => e.DeletedAt, "IX_ChefProfile_DeletedAt");

            entity.HasIndex(e => e.Code, "UQ_ChefProfile_Code").IsUnique();

            entity.HasIndex(e => e.UserId, "UQ_ChefProfile_UserId").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_ChefProfile_Uuid").IsUnique();

            entity.Property(e => e.Bio)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_ChefProfile_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.DeleteReason)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasDefaultValue("", "DF_ChefProfile_DeleteReason");
            entity.Property(e => e.DeletedAt).HasColumnType("smalldatetime");
            entity.Property(e => e.DisplayName)
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_ChefProfile_IsActive");
            entity.Property(e => e.Specialty)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_ChefProfile_Uuid");

            entity.HasOne(d => d.DeletedByUser).WithMany(p => p.ChefProfileDeletedByUsers)
                .HasForeignKey(d => d.DeletedByUserId)
                .HasConstraintName("FK_ChefProfile_DeletedByUser");

            entity.HasOne(d => d.User).WithOne(p => p.ChefProfileUser)
                .HasForeignKey<ChefProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChefProfile_AppUser");
        });

        modelBuilder.Entity<Cuisine>(entity =>
        {
            entity.ToTable("Cuisine");

            entity.HasIndex(e => e.Code, "UQ_Cuisine_Code").IsUnique();

            entity.HasIndex(e => e.Name, "UQ_Cuisine_Name").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_Cuisine_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_Cuisine_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.IconUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Cuisine_IsActive");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_Cuisine_Uuid");
        });

        modelBuilder.Entity<DailyRecipeStat>(entity =>
        {
            entity.ToTable(tb => tb.HasTrigger("TR_DailyRecipeStats_GenerateCode"));

            entity.HasIndex(e => e.StatsDate, "IX_DailyRecipeStats_StatsDate").IsDescending();

            entity.HasIndex(e => e.Code, "UQ_DailyRecipeStats_Code").IsUnique();

            entity.HasIndex(e => e.StatsDate, "UQ_DailyRecipeStats_StatsDate").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_DailyRecipeStats_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.GeneratedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_DailyRecipeStats_GeneratedAtUtc");
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_DailyRecipeStats_Uuid");
        });

        modelBuilder.Entity<Difficulty>(entity =>
        {
            entity.ToTable("Difficulty");

            entity.HasIndex(e => e.Code, "UQ_Difficulty_Code").IsUnique();

            entity.HasIndex(e => e.Name, "UQ_Difficulty_Name").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_Difficulty_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_Difficulty_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.IconUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Difficulty_IsActive");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_Difficulty_Uuid");
        });

        modelBuilder.Entity<FoodCategory>(entity =>
        {
            entity.ToTable("FoodCategory");

            entity.HasIndex(e => e.Code, "UQ_FoodCategory_Code").IsUnique();

            entity.HasIndex(e => e.Name, "UQ_FoodCategory_Name").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_FoodCategory_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_FoodCategory_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.Description)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.IconUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_FoodCategory_IsActive");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_FoodCategory_Uuid");
        });

        modelBuilder.Entity<Ingredient>(entity =>
        {
            entity.ToTable("Ingredient", tb => tb.HasTrigger("TR_Ingredient_GenerateCode"));

            entity.HasIndex(e => e.Code, "UQ_Ingredient_Code").IsUnique();

            entity.HasIndex(e => e.Name, "UQ_Ingredient_Name").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_Ingredient_Uuid").IsUnique();

            entity.Property(e => e.CaloriesPer100g).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Ingredient_IsActive");
            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_Ingredient_Uuid");

            entity.HasOne(d => d.DefaultUnit).WithMany(p => p.Ingredients)
                .HasForeignKey(d => d.DefaultUnitId)
                .HasConstraintName("FK_Ingredient_Unit");

            entity.HasOne(d => d.IngredientType).WithMany(p => p.Ingredients)
                .HasForeignKey(d => d.IngredientTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ingredient_IngredientType");
        });

        modelBuilder.Entity<IngredientImage>(entity =>
        {
            entity.ToTable("IngredientImage", tb => tb.HasTrigger("TR_IngredientImage_GenerateCode"));

            entity.HasIndex(e => e.IngredientId, "IX_IngredientImage_IngredientId");

            entity.HasIndex(e => e.Code, "UQ_IngredientImage_Code").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_IngredientImage_Uuid").IsUnique();

            entity.Property(e => e.AltText)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_IngredientImage_Uuid");

            entity.HasOne(d => d.Ingredient).WithMany(p => p.IngredientImages)
                .HasForeignKey(d => d.IngredientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IngredientImage_Ingredient");
        });

        modelBuilder.Entity<IngredientType>(entity =>
        {
            entity.ToTable("IngredientType");

            entity.HasIndex(e => e.Code, "UQ_IngredientType_Code").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_IngredientType_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_IngredientType_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.IconUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_IngredientType_IsActive");
            entity.Property(e => e.Label)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_IngredientType_Uuid");
        });

        modelBuilder.Entity<MoroccanCity>(entity =>
        {
            entity.ToTable("MoroccanCity", tb => tb.HasTrigger("TR_MoroccanCity_GenerateCode"));

            entity.HasIndex(e => e.RegionId, "IX_MoroccanCity_RegionId");

            entity.HasIndex(e => e.Code, "UQ_MoroccanCity_Code").IsUnique();

            entity.HasIndex(e => e.Name, "UQ_MoroccanCity_Name").IsUnique();

            entity.HasIndex(e => e.Slug, "UQ_MoroccanCity_Slug").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_MoroccanCity_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_MoroccanCity_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_MoroccanCity_IsActive");
            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Slug)
                .HasMaxLength(170)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_MoroccanCity_Uuid");

            entity.HasOne(d => d.Region).WithMany(p => p.MoroccanCities)
                .HasForeignKey(d => d.RegionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MoroccanCity_MoroccanRegion");
        });

        modelBuilder.Entity<MoroccanRegion>(entity =>
        {
            entity.ToTable("MoroccanRegion");

            entity.HasIndex(e => e.Code, "UQ_MoroccanRegion_Code").IsUnique();

            entity.HasIndex(e => e.Name, "UQ_MoroccanRegion_Name").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_MoroccanRegion_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_MoroccanRegion_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_MoroccanRegion_IsActive");
            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_MoroccanRegion_Uuid");
        });

        modelBuilder.Entity<PresetAvatarImage>(entity =>
        {
            entity.ToTable("PresetAvatarImage");

            entity.HasIndex(e => e.Code, "UQ_PresetAvatarImage_Code").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_PresetAvatarImage_Uuid").IsUnique();

            entity.Property(e => e.BackgroundColor)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_PresetAvatarImage_IsActive");
            entity.Property(e => e.Label)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_PresetAvatarImage_Uuid");
        });

        modelBuilder.Entity<Recipe>(entity =>
        {
            entity.ToTable("Recipe", tb => tb.HasTrigger("TR_Recipe_GenerateCode"));

            entity.HasIndex(e => e.ChefId, "IX_Recipe_ChefId");

            entity.HasIndex(e => e.CityId, "IX_Recipe_CityId");

            entity.HasIndex(e => e.CuisineId, "IX_Recipe_CuisineId");

            entity.HasIndex(e => e.DeletedAt, "IX_Recipe_DeletedAt");

            entity.HasIndex(e => e.DifficultyId, "IX_Recipe_DifficultyId");

            entity.HasIndex(e => e.Code, "UQ_Recipe_Code").IsUnique();

            entity.HasIndex(e => e.Slug, "UQ_Recipe_Slug").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_Recipe_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CoverImageUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_Recipe_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.DeleteReason)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasDefaultValue("", "DF_Recipe_DeleteReason");
            entity.Property(e => e.DeletedAt).HasColumnType("smalldatetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Recipe_IsActive");
            entity.Property(e => e.PublishedAt).HasColumnType("smalldatetime");
            entity.Property(e => e.Slug)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("DRAFT", "DF_Recipe_Status");
            entity.Property(e => e.Summary)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_Recipe_Uuid");
            entity.Property(e => e.Visibility)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PUBLIC", "DF_Recipe_Visibility");

            entity.HasOne(d => d.Chef).WithMany(p => p.Recipes)
                .HasForeignKey(d => d.ChefId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Recipe_ChefProfile");

            entity.HasOne(d => d.City).WithMany(p => p.Recipes)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK_Recipe_MoroccanCity");

            entity.HasOne(d => d.Cuisine).WithMany(p => p.Recipes)
                .HasForeignKey(d => d.CuisineId)
                .HasConstraintName("FK_Recipe_Cuisine");

            entity.HasOne(d => d.DeletedByUser).WithMany(p => p.Recipes)
                .HasForeignKey(d => d.DeletedByUserId)
                .HasConstraintName("FK_Recipe_DeletedByUser");

            entity.HasOne(d => d.Difficulty).WithMany(p => p.Recipes)
                .HasForeignKey(d => d.DifficultyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Recipe_Difficulty");

            entity.HasMany(d => d.FoodCategories).WithMany(p => p.Recipes)
                .UsingEntity<Dictionary<string, object>>(
                    "RecipeCategory",
                    r => r.HasOne<FoodCategory>().WithMany()
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_RecipeCategory_FoodCategory"),
                    l => l.HasOne<Recipe>().WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_RecipeCategory_Recipe"),
                    j =>
                    {
                        j.HasKey("RecipeId", "FoodCategoryId");
                        j.ToTable("RecipeCategory");
                    });
        });

        modelBuilder.Entity<RecipeImage>(entity =>
        {
            entity.ToTable("RecipeImage", tb => tb.HasTrigger("TR_RecipeImage_GenerateCode"));

            entity.HasIndex(e => e.RecipeId, "IX_RecipeImage_RecipeId");

            entity.HasIndex(e => e.Code, "UQ_RecipeImage_Code").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_RecipeImage_Uuid").IsUnique();

            entity.Property(e => e.AltText)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_RecipeImage_Uuid");

            entity.HasOne(d => d.Recipe).WithMany(p => p.RecipeImages)
                .HasForeignKey(d => d.RecipeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeImage_Recipe");
        });

        modelBuilder.Entity<RecipeIngredient>(entity =>
        {
            entity.HasKey(e => new { e.RecipeId, e.IngredientId });

            entity.ToTable("RecipeIngredient", tb => tb.HasTrigger("TR_RecipeIngredient_GenerateCode"));

            entity.HasIndex(e => e.IngredientId, "IX_RecipeIngredient_IngredientId");

            entity.HasIndex(e => e.Code, "UQ_RecipeIngredient_Code").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_RecipeIngredient_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Notes)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Quantity).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_RecipeIngredient_Uuid");

            entity.HasOne(d => d.Ingredient).WithMany(p => p.RecipeIngredients)
                .HasForeignKey(d => d.IngredientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeIngredient_Ingredient");

            entity.HasOne(d => d.Recipe).WithMany(p => p.RecipeIngredients)
                .HasForeignKey(d => d.RecipeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeIngredient_Recipe");

            entity.HasOne(d => d.Unit).WithMany(p => p.RecipeIngredients)
                .HasForeignKey(d => d.UnitId)
                .HasConstraintName("FK_RecipeIngredient_Unit");
        });

        modelBuilder.Entity<RecipeLike>(entity =>
        {
            entity.HasKey(e => new { e.RecipeId, e.UserId });

            entity.ToTable("RecipeLike");

            entity.HasIndex(e => e.UserId, "IX_RecipeLike_UserId");

            entity.Property(e => e.LikedAt)
                .HasDefaultValueSql("(getdate())", "DF_RecipeLike_LikedAt")
                .HasColumnType("smalldatetime");

            entity.HasOne(d => d.Recipe).WithMany(p => p.RecipeLikes)
                .HasForeignKey(d => d.RecipeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeLike_Recipe");

            entity.HasOne(d => d.User).WithMany(p => p.RecipeLikes)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeLike_AppUser");
        });

        modelBuilder.Entity<RecipeNutrition>(entity =>
        {
            entity.HasKey(e => e.RecipeId);

            entity.ToTable("RecipeNutrition");

            entity.HasIndex(e => e.Uuid, "UQ_RecipeNutrition_Uuid").IsUnique();

            entity.Property(e => e.RecipeId).ValueGeneratedNever();
            entity.Property(e => e.CaloriesPerServing).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CarbsGrams).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.FatGrams).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProteinGrams).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_RecipeNutrition_Uuid");

            entity.HasOne(d => d.Recipe).WithOne(p => p.RecipeNutrition)
                .HasForeignKey<RecipeNutrition>(d => d.RecipeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeNutrition_Recipe");
        });

        modelBuilder.Entity<RecipeShare>(entity =>
        {
            entity.ToTable("RecipeShare", tb => tb.HasTrigger("TR_RecipeShare_GenerateCode"));

            entity.HasIndex(e => e.SharedByUserId, "IX_RecipeShare_SharedByUserId");

            entity.HasIndex(e => e.Code, "UQ_RecipeShare_Code").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_RecipeShare_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ShareChannel)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.ShareMessage)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.SharedAt)
                .HasDefaultValueSql("(getdate())", "DF_RecipeShare_SharedAt")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_RecipeShare_Uuid");

            entity.HasOne(d => d.Recipe).WithMany(p => p.RecipeShares)
                .HasForeignKey(d => d.RecipeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeShare_Recipe");

            entity.HasOne(d => d.SharedByUser).WithMany(p => p.RecipeShareSharedByUsers)
                .HasForeignKey(d => d.SharedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeShare_SharedByUser");

            entity.HasOne(d => d.SharedWithUser).WithMany(p => p.RecipeShareSharedWithUsers)
                .HasForeignKey(d => d.SharedWithUserId)
                .HasConstraintName("FK_RecipeShare_SharedWithUser");
        });

        modelBuilder.Entity<RecipeStep>(entity =>
        {
            entity.ToTable("RecipeStep", tb => tb.HasTrigger("TR_RecipeStep_GenerateCode"));

            entity.HasIndex(e => e.Code, "UQ_RecipeStep_Code").IsUnique();

            entity.HasIndex(e => new { e.RecipeId, e.StepNumber }, "UQ_RecipeStep_Recipe_StepNumber").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_RecipeStep_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Instruction)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_RecipeStep_Uuid");

            entity.HasOne(d => d.Recipe).WithMany(p => p.RecipeSteps)
                .HasForeignKey(d => d.RecipeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeStep_Recipe");
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.ToTable("Unit");

            entity.HasIndex(e => e.Code, "UQ_Unit_Code").IsUnique();

            entity.HasIndex(e => e.Uuid, "UQ_Unit_Uuid").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DateInsert)
                .HasDefaultValueSql("(getdate())", "DF_Unit_DateInsert")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.DateModif).HasColumnType("smalldatetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Unit_IsActive");
            entity.Property(e => e.Label)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Uuid).HasDefaultValueSql("(newsequentialid())", "DF_Unit_Uuid");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
