using Foodiya.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace Foodiya.Infrastructure.Data;

public partial class AutoGeneratedDbContext
{
    public virtual DbSet<AppUserExternalLogin> AppUserExternalLogins { get; set; }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppUserExternalLogin>(entity =>
        {
            entity.ToTable("AppUserExternalLogin");

            entity.HasIndex(e => e.AppUserId, "IX_AppUserExternalLogin_AppUserId");
            entity.HasIndex(e => new { e.Provider, e.ProviderSubject }, "UQ_AppUserExternalLogin_Provider_Subject").IsUnique();
            entity.HasIndex(e => new { e.AppUserId, e.Provider }, "UQ_AppUserExternalLogin_AppUser_Provider").IsUnique();

            entity.Property(e => e.Provider).IsUnicode(false);
            entity.Property(e => e.ProviderSubject).IsUnicode(false);

            entity.Property(e => e.DateInsert).HasDefaultValueSql("(getdate())", "DF_AppUserExternalLogin_DateInsert");
            entity.Property(e => e.LastSignInAt).HasDefaultValueSql("(getdate())", "DF_AppUserExternalLogin_LastSignInAt");

            entity.HasOne(e => e.AppUser)
                .WithMany(user => user.ExternalLogins)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AppUserExternalLogin_AppUser");
        });
    }
}
