using System.Text.Json;
using Foodiya.Domain.Constants;
using Foodiya.Domain.Extensions;
using Foodiya.Domain.Models;
using Foodiya.Functions.Models;
using Foodiya.Infrastructure.Data;
using Microsoft.Azure.Functions.Worker;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Foodiya.Functions.Functions;

/// <summary>
/// ⏰ Timer-triggered function that runs every day at 2 AM UTC.
/// Computes daily recipe analytics and logs the results.
///
/// CRON: "0 0 2 * * *"  →  second minute hour day month weekday
///
/// What it does:
///   1. Counts total / published / new-today recipes.
///   2. Counts total likes placed today.
///   3. Finds the Top-5 most liked recipes (all time).
///   4. Finds the 5 most recently published recipes.
///   5. Aggregates recipe counts per cuisine and per difficulty.
///
/// In production you could persist the result to a "DailyStats" table,
/// push it to Azure Blob Storage, or send it to a dashboard webhook.
/// </summary>
public sealed class DailyRecipeStatsFunction
{
    private readonly AutoGeneratedDbContext _db;
    private readonly ILogger<DailyRecipeStatsFunction> _logger;

    public DailyRecipeStatsFunction(
        AutoGeneratedDbContext db,
        ILogger<DailyRecipeStatsFunction> logger)
    {
        _db = db;
        _logger = logger;
    }

    /// <param name="timerInfo">
    /// Injected by the Azure Functions runtime.  Contains the schedule
    /// status (last run, next run, whether the run was late).
    /// </param>
    [Function(nameof(DailyRecipeStatsFunction))]
    public async Task RunAsync(
        [TimerTrigger("0 0 2 * * *")] TimerInfo timerInfo,
        CancellationToken ct)
    {
        _logger.LogInformation("⏰ DailyRecipeStatsFunction started at {UtcNow}", DateTime.UtcNow);

        var today = DateTime.UtcNow.Date;

        // ── 1. Totals ───────────────────────────────────────
        var totalRecipes = await _db.Recipes
            .CountAsync(r => r.IsActive && r.DeletedAt == null, ct);

        var totalPublished = await _db.Recipes
            .CountAsync(r => r.IsActive && r.DeletedAt == null && r.Status == RecipeStatusConstants.Published, ct);

        var newToday = await _db.Recipes
            .CountAsync(r => r.IsActive && r.DeletedAt == null && r.DateInsert >= today, ct);

        var likesToday = await _db.RecipeLikes
            .CountAsync(l => l.LikedAt >= today, ct);

        // ── 2. Top-5 most liked recipes (all time) ──────────
        var topLiked = await _db.Recipes
            .Where(r => r.IsActive && r.DeletedAt == null && r.Status == RecipeStatusConstants.Published)
            .OrderByDescending(r => r.RecipeLikes.Count)
            .Take(5)
            .Select(r => new RecipeStatItem
            {
                RecipeId = r.Id,
                Title = r.Title,
                ChefDisplayName = r.Chef.DisplayName,
                LikeCount = r.RecipeLikes.Count,
                PublishedAt = r.PublishedAt ?? r.DateInsert
            })
            .ToListAsync(ct);

        // ── 3. 5 most recently published recipes ────────────
        var recentRecipes = await _db.Recipes
            .Where(r => r.IsActive && r.DeletedAt == null && r.Status == RecipeStatusConstants.Published)
            .OrderByDescending(r => r.PublishedAt)
            .Take(5)
            .Select(r => new RecipeStatItem
            {
                RecipeId = r.Id,
                Title = r.Title,
                ChefDisplayName = r.Chef.DisplayName,
                LikeCount = r.RecipeLikes.Count,
                PublishedAt = r.PublishedAt ?? r.DateInsert
            })
            .ToListAsync(ct);

        // ── 4. Recipes per cuisine ──────────────────────────
        var byCuisine = await _db.Cuisines
            .Where(c => c.IsActive)
            .Select(c => new CuisineStatItem
            {
                CuisineId = c.Id,
                CuisineName = c.Name,
                RecipeCount = c.Recipes.Count(r => r.IsActive && r.DeletedAt == null)
            })
            .OrderByDescending(c => c.RecipeCount)
            .ToListAsync(ct);

        // ── 5. Recipes per difficulty ───────────────────────
        var byDifficulty = await _db.Difficulties
            .Where(d => d.IsActive)
            .Select(d => new DifficultyStatItem
            {
                DifficultyName = d.Name,
                RecipeCount = d.Recipes.Count(r => r.IsActive && r.DeletedAt == null)
            })
            .OrderByDescending(d => d.RecipeCount)
            .ToListAsync(ct);

        // ── Build result ────────────────────────────────────
        var stats = new DailyRecipeStatsResult
        {
            GeneratedAtUtc = DateTime.UtcNow,
            TotalRecipes = totalRecipes,
            TotalPublishedRecipes = totalPublished,
            NewRecipesToday = newToday,
            TotalLikesToday = likesToday,
            TopLikedRecipes = topLiked,
            RecentRecipes = recentRecipes,
            TopCuisines = byCuisine,
            RecipesByDifficulty = byDifficulty
        };

        var jsonOptions = new JsonSerializerOptions { WriteIndented = true };

        // Log the full stats as structured JSON
        _logger.LogInformation(
            "📊 Daily Stats: {Stats}",
            JsonSerializer.Serialize(stats, jsonOptions));

        // ── Persist to DailyRecipeStats table ───────────────
        var dailyRecord = new DailyRecipeStat
        {
            StatsDate = today,
            GeneratedAtUtc = stats.GeneratedAtUtc,
            TotalRecipes = totalRecipes,
            TotalPublishedRecipes = totalPublished,
            NewRecipesToday = newToday,
            TotalLikesToday = likesToday,
            TopLikedRecipesJson = JsonSerializer.Serialize(topLiked, jsonOptions),
            RecentRecipesJson = JsonSerializer.Serialize(recentRecipes, jsonOptions),
            CuisineBreakdownJson = JsonSerializer.Serialize(byCuisine, jsonOptions),
            DifficultyBreakdownJson = JsonSerializer.Serialize(byDifficulty, jsonOptions),
            Code = EntityCodeGenerator.For("DRS")
        };

        // Upsert: if a row for today already exists (e.g. manual re-run), update it.
        var existing = await _db.DailyRecipeStats
            .FirstOrDefaultAsync(d => d.StatsDate == dailyRecord.StatsDate, ct);

        if (existing is not null)
        {
            existing.GeneratedAtUtc = dailyRecord.GeneratedAtUtc;
            existing.TotalRecipes = dailyRecord.TotalRecipes;
            existing.TotalPublishedRecipes = dailyRecord.TotalPublishedRecipes;
            existing.NewRecipesToday = dailyRecord.NewRecipesToday;
            existing.TotalLikesToday = dailyRecord.TotalLikesToday;
            existing.TopLikedRecipesJson = dailyRecord.TopLikedRecipesJson;
            existing.RecentRecipesJson = dailyRecord.RecentRecipesJson;
            existing.CuisineBreakdownJson = dailyRecord.CuisineBreakdownJson;
            existing.DifficultyBreakdownJson = dailyRecord.DifficultyBreakdownJson;

            _logger.LogInformation("🔄 Updated existing DailyRecipeStats row for {Date}", today);
        }
        else
        {
            _db.DailyRecipeStats.Add(dailyRecord);
            _logger.LogInformation("➕ Inserted new DailyRecipeStats row for {Date}", today);
        }

        await _db.SaveChangesAsync(ct);

        // ────────────────────────────────────────────────────
        // TODO (production ideas):
        //   • Push JSON to Azure Blob Storage.
        //   • Send to a Slack / Teams webhook for the team dashboard.
        // ────────────────────────────────────────────────────

        _logger.LogInformation(
            "✅ DailyRecipeStatsFunction completed — {Total} recipes, {Published} published, {New} new today, {Likes} likes today",
            totalRecipes, totalPublished, newToday, likesToday);
    }
}
