using Foodiya.Functions.Models;
using Foodiya.Infrastructure.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Foodiya.Functions.Functions;

/// <summary>
/// 📊 HTTP-triggered function that calculates recipe nutrition totals
///    based on a list of ingredients and their quantities.
///
/// Endpoint:  POST /api/nutrition/calculate
///
/// HOW IT WORKS:
///   1. Client sends a JSON body with servings count and a list of
///      ingredients (each with IngredientId and QuantityGrams).
///   2. The function looks up CaloriesPer100g for each ingredient
///      from the database.
///   3. It computes per-ingredient and total calories, then divides
///      by servings for the per-serving figure.
///
/// This is a great candidate for a standalone function because:
///   • It's stateless and self-contained.
///   • It can be called by your API, your frontend, or a mobile app.
///   • It scales independently of your main API.
///
/// EXAMPLE REQUEST:
///   POST /api/nutrition/calculate
///   {
///     "servings": 4,
///     "ingredients": [
///       { "ingredientId": 1, "quantityGrams": 200 },
///       { "ingredientId": 5, "quantityGrams": 150 },
///       { "ingredientId": 12, "quantityGrams": 50 }
///     ]
///   }
///
/// EXAMPLE RESPONSE:
///   {
///     "servings": 4,
///     "totalCalories": 685.00,
///     "caloriesPerServing": 171.25,
///     "breakdown": [
///       { "ingredientId": 1, "ingredientName": "Chicken Breast", "quantityGrams": 200, "calories": 330.00 },
///       { "ingredientId": 5, "ingredientName": "Rice",           "quantityGrams": 150, "calories": 195.00 },
///       { "ingredientId": 12,"ingredientName": "Olive Oil",      "quantityGrams": 50,  "calories": 160.00 }
///     ]
///   }
/// </summary>
public sealed class NutritionCalculatorFunction
{
    private readonly AutoGeneratedDbContext _db;
    private readonly ILogger<NutritionCalculatorFunction> _logger;

    public NutritionCalculatorFunction(
        AutoGeneratedDbContext db,
        ILogger<NutritionCalculatorFunction> logger)
    {
        _db = db;
        _logger = logger;
    }

    [Function("NutritionCalculate")]
    public async Task<IActionResult> RunAsync(
        [HttpTrigger(AuthorizationLevel.Function, "post", Route = "nutrition/calculate")] HttpRequest req,
        CancellationToken ct)
    {
        _logger.LogInformation("📊 NutritionCalculatorFunction invoked");

        // ── 1. Parse & validate ─────────────────────────────
        NutritionCalculatorRequest? request;
        try
        {
            request = await req.ReadFromJsonAsync<NutritionCalculatorRequest>(ct);
        }
        catch
        {
            return new BadRequestObjectResult(new { error = "Invalid JSON body." });
        }

        if (request is null || request.Ingredients.Count == 0)
            return new BadRequestObjectResult(new { error = "At least one ingredient is required." });

        if (request.Servings <= 0)
            return new BadRequestObjectResult(new { error = "Servings must be greater than zero." });

        // ── 2. Fetch ingredients from DB ────────────────────
        var ingredientIds = request.Ingredients
            .Select(i => i.IngredientId)
            .Distinct()
            .ToList();

        var dbIngredients = await _db.Ingredients
            .Where(i => ingredientIds.Contains(i.Id) && i.IsActive)
            .Select(i => new { i.Id, i.Name, i.CaloriesPer100g })
            .ToDictionaryAsync(i => i.Id, ct);

        // ── 3. Compute nutrition per ingredient ─────────────
        var breakdown = new List<NutritionIngredientDetail>();

        foreach (var input in request.Ingredients)
        {
            if (!dbIngredients.TryGetValue(input.IngredientId, out var dbIng))
            {
                _logger.LogWarning("Ingredient {Id} not found or inactive — skipped", input.IngredientId);
                continue;
            }

            // CaloriesPer100g can be null in the schema → treat null as 0
            var caloriesPer100 = dbIng.CaloriesPer100g ?? 0m;
            var calories = caloriesPer100 * input.QuantityGrams / 100m;

            breakdown.Add(new NutritionIngredientDetail
            {
                IngredientId = dbIng.Id,
                IngredientName = dbIng.Name,
                QuantityGrams = input.QuantityGrams,
                Calories = Math.Round(calories, 2)
            });
        }

        // ── 4. Build response ───────────────────────────────
        var totalCalories = breakdown.Sum(b => b.Calories);

        var response = new NutritionCalculatorResponse
        {
            Servings = request.Servings,
            TotalCalories = Math.Round(totalCalories, 2),
            CaloriesPerServing = Math.Round(totalCalories / request.Servings, 2),
            Breakdown = breakdown
        };

        _logger.LogInformation(
            "✅ Nutrition calculated — {Count} ingredients, {Total} total kcal, {PerServing} per serving",
            breakdown.Count, response.TotalCalories, response.CaloriesPerServing);

        return new OkObjectResult(response);
    }
}
